name: droidian rootfs-builder

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - '**'
    tags:
      - '**'
  schedule:
    - cron: "59 23 * * *"

jobs:
  once:
    runs-on: ubuntu-latest
    name: Generate matrix
    outputs:
      matrix: ${{ steps.gen-matrix.outputs.matrix }}
      rootfs_t_url: ${{ steps.configure-submodules.outputs.rootfs_t_url }}
      device_t_url: ${{ steps.configure-submodules.outputs.device_t_url }}
      droidian_version: ${{ steps.detect_droidian_version.outputs.version }}
      is_nightly: ${{ steps.detect_release_type.outputs.is_nightly }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: false
          fetch-tags: ${{ github.ref_type != 'tag' }} # avoids conflict on tag push

      - name: Configure submodules
        id: configure-submodules
        run: |
          # Fallback defaults
          DEVICE_T_URL="False"

          GH_OWNER="${{ github.repository_owner}}"
          # Define default url's
          ROOTFS_T_URL="https://github.com/droidian-releng/rootfs-templates.git"
          DEVICE_T_URL="https://github.com/droidian-releng/droidian-device-templates.git"
          # Define forked url's
          ROOTFS_T_URL_FORK="https://github.com/$GH_OWNER/rootfs-templates.git"
          DEVICE_T_URL_FORK="https://github.com/$GH_OWNER/droidian-device-templates.git"
          # Check url's
          echo "Checking 'rootfs-templates' fork url..."
          if git ls-remote --exit-code "${ROOTFS_T_URL_FORK}" HEAD &>/dev/null; then
            echo "Fork detected for 'rootfs-templates'"
            ROOTFS_T_URL="${ROOTFS_T_URL_FORK}"
          fi
          echo "Checking 'drioidian-device-templates' url..."
          if git ls-remote --exit-code "${DEVICE_T_URL_FORK}" HEAD &>/dev/null; then
            echo "Fork detected for 'droidian-device-templates'"
            DEVICE_T_URL="${DEVICE_T_URL_FORK}"
          elif git ls-remote --exit-code "${DEVICE_T_URL}" HEAD &>/dev/null; then
            echo "Upstream detected for 'device-templates'"
            DEVICE_T_URL="${DEVICE_T_URL}"
          else
            echo "No repository found for 'device-templates' Disabling..."
            DEVICE_T_URL="False"
          fi
          echo "ROOTFS_T_URL = ${ROOTFS_T_URL}"
          echo "DEVICE_T_URL = ${DEVICE_T_URL}"
          # Configure submodule url's
          git config --file=.gitmodules submodule.rootfs-templates.url ${ROOTFS_T_URL}
          if [[ "${DEVICE_T_URL}" != "False" ]]; then
            git submodule add ${DEVICE_T_URL} device-templates
          fi
          # Export final submodule urls to gh outputs
          echo "rootfs_t_url=${ROOTFS_T_URL}" >> $GITHUB_OUTPUT
          echo "device_t_url=${DEVICE_T_URL}" >> $GITHUB_OUTPUT
          echo "DEVICE_T_URL=${DEVICE_T_URL}" >> GITHUB_ENV

      - name: Checkout submodules
        run: |
          git submodule sync --recursive
          git submodule update --init --recursive
          if [[ "${DEVICE_T_URL}" != "False" ]] && [[ -e "device-templates/community_devices.yml" ]]; then
            # Copy community_devices to parent
            cp -v device-templates/community_devices.yml .
          fi

      - name: Detect release type
        id: detect_release_type
        run: |
          # Release type: nightly only on scheduled
          if [[ "${{github.event_name}}" == "schedule" ]]; then
            echo "is_nightly=true" >> $GITHUB_OUTPUT
            echo "Release type: Nightly"
          else
            echo "is_nightly=false" >> $GITHUB_OUTPUT
            echo "Release type: Release (Draft)"
          fi

      - name: Detect Droidian version
        id: detect_droidian_version
        run: |
          # Check if triggered by tag push
          if [[ "${{ github.ref }}" == refs/tags/* ]]; then
            FULL_TAG_REF="${{ github.ref }}"
            TAG_NAME="${FULL_TAG_REF#refs/tags/}"
          else
            # No tag push, check if HEAD has a tag
            TAG_NAME=$(git tag --points-at HEAD | head -n 1)
          fi
          # Determine the valid version to use
          if [[ -n "$TAG_NAME" ]]; then
            # Split tag to release/version_variant
            # Get release before last '/' separator
            TAG_RELEASE="${TAG_NAME%%/*}"  # Reserved for future use (e.g., "droidian")
            # Get TAG_VERSION_FULL before last '/' separator
            TAG_VERSION_FULL="${TAG_NAME#*/}"
            if [[ "$TAG_VERSION_FULL" == *_* ]]; then
              TAG_VERSION="${TAG_VERSION_FULL%%_*}"
              TAG_VERSION_VARIANT="${TAG_VERSION_FULL#*_}" # Reserved for future use
            else
              TAG_VERSION="${TAG_VERSION_FULL}"
              TAG_VERSION_VARIANT="" # Reserved for future use
            fi

            # Validate and set the version
            if [[ "$TAG_VERSION" =~ ^(current|next)$ ]]; then
              VALID_VERSION="$TAG_VERSION"
            # int versions from snap 99 are allowed
            elif [[ -n "${TAG_VERSION}" ]] && [ "${TAG_VERSION}" -eq "${TAG_VERSION}" ] 2>/dev/null; then
              echo "TAG_VERSION It's an integer"
              if [ "$TAG_VERSION" -ge 99 ]; then
                VALID_VERSION="$TAG_VERSION"
              else
                # No valid int version, fallback to next
                echo "Fallback to next: Invalid numeric version in tag"
                VALID_VERSION="next"
                echo "Invalid version \"${TAG_VERSION}\""
              fi
            else
              # No valid version, fallback to next
              echo "Fallback to next: No valid version found in tag"
              VALID_VERSION="next"
            fi
          elif [[ "${{github.event_name}}" == "schedule" ]]; then

            echo "Use next: Scheduled trigger"
            VALID_VERSION="next"
          else
            # Fallback to next
            echo "Fallback to next: No tag detected"
            VALID_VERSION="next"
          fi

          # Export version to github env
          echo "version=${VALID_VERSION}" >> $GITHUB_OUTPUT
          # Debug outputs
          echo "FULL_TAG_REF detected: ${FULL_TAG_REF}"
          echo "TAG_NAME detected: ${TAG_NAME}"
          echo "TAG_RELEASE detected: ${TAG_RELEASE}"
          echo "TAG_VERSION_FULL detected: ${TAG_VERSION_FULL}"
          echo "VALID VERSION detected: ${VALID_VERSION}"
          echo "TAG_VERSION_VARIANT detected: ${TAG_VERSION_VARIANT}"

      - name: Generate matrix
        id: gen-matrix
        run: |
          JOBS="$(./generate_device_recipe.py --matrix)"
          echo "matrix=${JOBS}" >> $GITHUB_OUTPUT

  build:
    runs-on: ubuntu-24.04-arm
    needs: once

    strategy:
      fail-fast: true
      matrix:
        config: ${{ fromJson(needs.once.outputs.matrix) }}

    name: ${{ matrix.config.job_name }}

    steps:
      - name: Get current date
        run: echo "current_date=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - name: Set suffix
        run: echo "release_suffix=_${{ env.current_date }}" >> $GITHUB_ENV

      - name: Set Nightly version
        if: needs.once.outputs.is_nightly == 'true'
        run: echo "DROIDIAN_VERSION=${{ needs.once.outputs.droidian_version }}" >> $GITHUB_ENV

      - name: Set Release version
        if: needs.once.outputs.is_nightly == 'false'
        run: echo "DROIDIAN_VERSION=${{ needs.once.outputs.droidian_version }}" >> $GITHUB_ENV

      - name: Set identifier
        run: echo "DROIDIAN_IDENTIFIER=${{ matrix.config.product }}-${{ matrix.config.arch }}-${{ matrix.config.edition }}-${{ matrix.config.variant }}-${{ matrix.config.apilevel }}" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: 'true'
          submodules: false

      - name: Configure submodules
        id: configure-submodules
        run: |
          ROOTFS_T_URL="${{ needs.once.outputs.rootfs_t_url }}"
          DEVICE_T_URL="${{ needs.once.outputs.device_t_url }}"
          echo "ROOTFS_T_URL = ${ROOTFS_T_URL}"
          echo "DEVICE_T_URL = ${DEVICE_T_URL}"
          # Configure submodule url's
          git config --file=.gitmodules submodule.rootfs-templates.url ${ROOTFS_T_URL}
          if [[ "${DEVICE_T_URL}" != "False" ]]; then
            git submodule add ${DEVICE_T_URL} device-templates
          fi
          # Export device templates url var to github env
          echo "DEVICE_T_URL=${DEVICE_T_URL}" >> GITHUB_ENV

      - name: Checkout submodules
        run: |
          git submodule sync --recursive
          git submodule update --init --recursive --remote

      - name: Create build dir
        run: mkdir -p /tmp/buildd-results

      - name: Pull container
        run: docker pull quay.io/droidian/rootfs-builder:next-arm64

      - name: Start Container
        run: echo CONTAINER_HASH=$(docker run --detach --privileged --cgroupns=host -v /tmp/buildd-results:/buildd/out -v /dev:/host-dev -v /sys/fs/cgroup:/sys/fs/cgroup -v ${PWD}:/buildd/sources --security-opt seccomp:unconfined quay.io/droidian/rootfs-builder:next-arm64 sleep infinity) >> $GITHUB_ENV

      - name: Configure Container ENV
        run: |
          SETENV_SCRIPT="device-templates/setenv-gh-container.sh"
           if [[ -e "${SETENV_SCRIPT}" ]]; then
             echo "Script found: ${SETENV_SCRIPT}"
             docker exec $CONTAINER_HASH /bin/sh -c "cd /buildd/sources && chmod a+x /buildd/sources/${SETENV_SCRIPT} && . ${SETENV_SCRIPT}"
           else
             echo "Script not found: ${SETENV_SCRIPT} Skipping..."
           fi

      - name: Build rootfs
        run: |
          docker exec $CONTAINER_HASH /bin/sh -c 'cd /buildd/sources; DROIDIAN_VERSION="${{ env.DROIDIAN_VERSION }}" ./generate_device_recipe.py ${{ matrix.config.product }} ${{ matrix.config.arch }} ${{ matrix.config.edition }} ${{ matrix.config.variant }} ${{ matrix.config.apilevel }} ${{ matrix.config.droidian_variant }} && debos --disable-fakemachine generated/droidian.yaml'

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: droidian-out-${{ matrix.config.product }}-${{ matrix.config.arch }}-${{ matrix.config.edition }}-${{ matrix.config.variant }}-${{ matrix.config.apilevel }}
          path: out/*
          if-no-files-found: error
          retention-days: 1

  prepare:
    runs-on: ubuntu-latest
    name: Create GitHub release
    needs: [once, build]
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}${{ steps.create_nightly.outputs.upload_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Free up some storage
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          swap-storage: true

      - name: Nightly tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: needs.once.outputs.is_nightly == 'true'
        run: |
          gh release delete nightly --yes | true
          git push --delete origin refs/tags/nightly || true
          gh release create nightly

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: droidian-out

      - name: Create SHA256SUMS
        run: |
          cd droidian-out
          for x in droidian-out-*; do
            cd $x
            sha256sum * >> ../SHA256SUMS
            cd ..
          done

      - name: Create stable release (drafted)
        id: create_release
        if: needs.once.outputs.is_nightly == 'false'
        uses: softprops/action-gh-release@v2.2.2
        with:
          files: droidian-out/SHA256SUMS
          tag_name: ${{ github.ref }}
          draft: true
          prerelease: false

      - name: Create nightly release
        id: create_nightly
        if: needs.once.outputs.is_nightly == 'true'
        uses: softprops/action-gh-release@v2.2.2
        with:
          files: droidian-out/SHA256SUMS
          tag_name: nightly
          draft: false
          prerelease: true

  publish:
    runs-on: ubuntu-latest
    needs: [once, prepare]
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}${{ steps.create_nightly.outputs.upload_url }}

    strategy:
      fail-fast: false
      matrix:
        config: ${{ fromJson(needs.once.outputs.matrix) }}

    name: Publish ${{ matrix.config.job_name }}

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: droidian-out-${{ matrix.config.product }}-${{ matrix.config.arch }}-${{ matrix.config.edition }}-${{ matrix.config.variant }}-${{ matrix.config.apilevel }}
          path: droidian-out

      - name: Create stable release (drafted)
        id: create_release
        if: needs.once.outputs.is_nightly == 'false'
        uses: softprops/action-gh-release@v2.2.2
        with:
          files: droidian-out/*
          tag_name: ${{ github.ref }}
          draft: true
          prerelease: false

      - name: Create nightly release
        id: create_nightly
        if: needs.once.outputs.is_nightly == 'true'
        uses: softprops/action-gh-release@v2.2.2
        with:
          files: droidian-out/*
          tag_name: nightly
          draft: false
          prerelease: true
